### ISSUE TITLE
batchQuery Error

### ISSUE THREAD

**Issue by nazarenkoartem** [conwetlab/ngsijs#17]
Dear Developers,

I've already wrote you about a problem with "getEntityAttribute". Thank you very much for fixing this. However now I faced new difficulty with following method:

"batchQuery"

The problem is something is wrong with connection and request processing, the curl:

`curl -s -H "Content-Type: application/json" -X POST -d '{"bodyParams": {"options": {}}}' http://localhost:3000/accessfunctionality/orion/batchQuery`

Error:

`{"status":"error","message":"Unexpected error code: 400"}`

NGSI.Connection:

batchQuery(connection, params){
     return new Promise(function(resolve, reject){
       console.log('NGSI function call: batchQuery');
 
       connection.v2.batchQuery(params.options).then(
         (response) => {
           resolve(response);
         }, (error) => {
           reject(error);
         }
       );
     });
   }

Tried some testing:

 `batchQuery(connection, params){
    return new Promise(function(resolve, reject){
      console.log('NGSI function call: batchQuery');
		console.log(params);
      connection.v2.batchQuery(params.options).then(
        (response) => {
		console.log("correct");
          resolve(response);
        }, (error) => {
			console.log("error error error error");
          reject(error);
        }
      );
    });
  }`

Result:

`controller: AccessFunctionality
NGSI connection
NGSI function call: batchQuery
{ options: {} }
error error error error
POST /accessfunctionality/orion/batchQuery 200 155.687 ms - 57
Executing (default): INSERT INTO "Performances" ("id","component","name","service","executionTime","status","errorMessage","createdAt") VALUES (DEFAULT,'Enabler','orion','batchQuery',76.60613,'Error','Unexpected error code: 400','2017-11-13 15:54:20.210 +00:00') RETURNING *;
Executing (default): INSERT INTO "Performances" ("id","component","service","executionTime","status","createdAt") VALUES (DEFAULT,'Enablers Framework','/accessfunctionality/orion/batchQuery',158.707139,'Success','2017-11-13 15:54:20.214 +00:00') RETURNING *;`

When testing without parameters:

` batchQuery(connection, params){
    return new Promise(function(resolve, reject){
      console.log('NGSI function call: batchQuery');

      connection.v2.batchQuery().then(
        (response) => {
          resolve(response);
        }, (error) => {
          reject(error);
        }
      );
    });
  }`

Throws an error (as also stated in documentation: "query is empty" - this part is working well according docs):

`{"status":"error","message":"missing query parameter"}`

I will be grateful, if you could help me, and point what is wrong. Thank you in advance!

N.B.

"batchUpdate" works well, I already tested it, but has an additional parameter "changes". And entities to be updated can be delivered inside this parameter.

**Comment by aarranz** [comment]
Hi nazarenkoartem,

so, your problem is that the library doesn't throw an exception before connecting to the context broker server when providing an empty dictionary as query parameter, right?

Best Regards

**Comment by nazarenkoartem** [comment]
Dear aarranz,

Nope, this is not a problem. My problem is, it always throws an 400 error, while sending empty dictionary as query parameter or not. As I understand, empty dictionary means that it should just return first 20 records.

I am not sure where the problem is, as I wrote "batchUpdate" works well, but it has additional parameter "changes". An example with empty "options" parameter:

`curl -s -H "Content-Type: application/json" -X POST -d '{"bodyParams": {"changes": {"actionType": "APPEND", "entities": [{"type": "LED", "id": "LED002", "brightness": {"value": "12"}},{"type": "LED", "id": "LED003", "brightness": {"value": "18"}} ]}, "options": {}}}' http://localhost:3000/accessfunctionality/orion/batchUpdate`

The problem might be also, as it is not possible to define, as in the documentation, the exact records to be returned. In the above mentioned example I can define concrete entities ("LED002", "LED003") and attributes ("brightness") to be updated. 

Again, while sending an empty object I cannot get first 20 entities from context broker, if I try to define which entities I need, for instance (LED002, LED003), there is no option in "options" parameter to define the entities to be returned, as in your example (entities and attributes are not the options of "options" parameter):

`"entities": [
       {
           "idPattern": ".*",
           "type": "myFooType"
       },
       {
           "id": "myBar",
           "type": "myBarType"
       }
   ],
   "attributes": [
       "temperature",
       "humidity"
   ]`

I apologize in advance, if I am not very clear.

Best regards

Artem

**Comment by aarranz** [comment]
Hi @nazarenkoartem,

Sorry for the delay, but we are a bit busy these days. We have updated the `batchQuery` documentation and its implementation, now it should work with empty queries.

On the other hand, I were testing it using real queries (that is, providing the `entities` option) and it seems to be working as expected. E.g. `connection.v2.batchQuery({entities: [{'idPattern': '.*', 'type': 'AirQualityObserved'}]})`. Do you have more details of the error you are getting or the parameters you were using?

Best regards,

**Comment by aarranz** [comment]
Closing for now. Reopen it, if you still have problems (providing more details).

Cheers.
