### ISSUE TITLE
Support for geo-queries in v2.listEntities([options])

### ISSUE THREAD

**Issue by fgalan** [conwetlab/ngsijs#27]
According to documentation at http://conwetlab.github.io/ngsijs/stable/NGSI.Connection.html#.%22v2.listEntities%22__anchor, the supported options are:

```
    attrs (String): Comma-separated list of attribute names whose data are to be included in the response. The attributes are retrieved in the order specified by this parameter. If this parameter is not included, the attributes are retrieved in arbitrary order.
    correlator (String): Transaction id
    count (Boolean; default: false): Request total count
    id (String): A comma-separated list of entity ids to retrieve. Incompatible with the idPattern option.
    idPattern (String): A correctly formated regular expression. Retrieve entities whose ID matches the regular expression. Incompatible with the id option
    limit (Number; default: 20): This option allow you to specify the maximum number of entities you want to receive from the server
    offset (Number; default: 0): Allows you to skip a given number of elements at the beginning
    metadata (String): A comma-separated list of metadata names to include in the response
    mq (String): A query expression for attribute metadata, composed of a list of statements separated by semicolons (;)
    orderBy (String): Criteria for ordering results
    q (String): A query expression, composed of a list of statements separated by semicolons (;)
    service (String): Service/tenant to use in this operation
    servicepath (String): Service path to use in this operation
    type (String): A comma-separated list of entity types to retrieve. Incompatible with the typePattern option.
    typePattern (String): A correctly formated regular expression. Retrieve entities whose type matches the regular expression. Incompatible with the type option.
    unique (Boolean): Represent entities as an array of non-repeated attribute values.
    values (Boolean): Represent entities as an array of attribute values
```

However, what about geometry, georel and coords? They aren't in the list and are needed to get advantages of one of the most important features of Orion Context Broker: geo queries.

Is this a gap in the current implementation of the library? Or a gap in the documentation?

Thanks!

**Comment by fgalan** [comment]
Seems to be a gap in documentation, as the three parameters appears in the code (https://github.com/conwetlab/ngsijs/blob/f2678de45763f7c428c7415c62efa083b9685b55/NGSI.js#L3008):

```
        parameters.georel = options.georel;
        parameters.geometry = options.geometry;
        parameters.coords = options.coords;
```

**Comment by fgalan** [comment]
PR fixing the documentation gap: https://github.com/conwetlab/ngsijs/pull/28

**Comment by aarranz** [comment]
Thanks for reporting the problem and for providing a PR for fixing it 😄.

**Comment by fgalan** [comment]
Not sure if my PR has fixes it... Looking to http://conwetlab.github.io/ngsijs/stable/NGSI.Connection.html#.%22v2.listEntities%22__anchor it seems to be the seem that before (i.e. geo-parameters are not shown).

Maybe some documentation build process has to be done to update that page?

**Comment by aarranz** [comment]
Sorry for the delay. Documentation updates are live now that v1.2.2 has been released.

**Comment by fgalan** [comment]
Now I see georel, goemetry and coords in http://conwetlab.github.io/ngsijs/stable/NGSI.Connection.html#.%22v2.listEntities%22__anchor... perfect! :D
