### ISSUE TITLE
node-js client does not work with Orion context broker

### ISSUE THREAD

**Issue by rianwouters** [conwetlab/ngsijs#3]
When using the node-js client with Orion, I get the following:

time=2016-05-11T11:36:53.780UTC | lvl=WARNING | corr=a8d4baac-176c-11e6-9e73-029d61bc569f | trans=1462965567-845-00000000086 | srv=<default> | subsrv=<default> | from=127.0.0.1 | function=badInputReset | comp=Orion | msg=AlarmManager.caising alarm BadInput 127.0.0.1: no valid 'Accept-format' found

This is caused by the fact the Accept format is set to applicaiton/xml, which is not supported by Orion

**Comment by aarranz** [comment]
I've uploaded a new version to npm :)

**Comment by rianwouters** [comment]
thanks!
