### ISSUE TITLE
Empty contextValue is wrongly translated

### ISSUE THREAD

**Issue by rianwouters** [conwetlab/ngsijs#5]
in ngsi_build_update_context_request:
`
 if (contextValue.trim() === '') {
    attributeElement.valuecontextValue = 'emptycontent';
  }
`
should be 

`
 if (contextValue.trim() === '') {
    contextValue = 'emptycontent';
  }
`

No tests failing?

**Comment by rianwouters** [comment]
#4

**Comment by aarranz** [comment]
I've no tested the current version of the Orion context broker, but previous versions didn't support empty values.

This code is not breaking any test because this behaviour was negotiated with @fgalan, but probably it can be removed now :-), I'll check it.

**Comment by aarranz** [comment]
Ops, I didn't noticed it was a bug, independently of using the `emptycontent` string for the empty value. I'll work on it tomorrow.

**Comment by rianwouters** [comment]
I believe alsof the emptycontent should really be an empty string or even null, dont you think?

Verzonden van mijn HTC

----- Reply message -----
Van: "Álvaro Arranz" <notifications@github.com>
Aan: "conwetlab/ngsijs" <ngsijs@noreply.github.com>
CC: "rianwouters" <rianwouters@hotmail.com>, "Author" <author@noreply.github.com>
Onderwerp: [conwetlab/ngsijs] Empty contextValue is wrongly translated (#5)
Datum: wo, mei 11, 2016 21:38


Ops, I didn't noticed it was a bug, independently of using the `emptycontent` string for the empty value. I'll work on it tomorrow.

---

**Comment by rianwouters** [comment]
Van hou explain why you use emptycontent for the empty string?


Verzonden van mijn HTC

----- Reply message -----
Van: "Álvaro Arranz" <notifications@github.com>
Aan: "conwetlab/ngsijs" <ngsijs@noreply.github.com>
CC: "rianwouters" <rianwouters@hotmail.com>, "Author" <author@noreply.github.com>
Onderwerp: [conwetlab/ngsijs] Empty contextValue is wrongly translated (#5)
Datum: wo, mei 11, 2016 21:38


Ops, I didn't noticed it was a bug, independently of using the `emptycontent` string for the empty value. I'll work on it tomorrow.

---

**Comment by rianwouters** [comment]
Hi,
thanks for your swift responses until now :-)
Just checked the OMA NGSI specs:
For each ContextElement of the list of Context Elements received in the updateContextRequest, if an empty Context Value is
provided, the operation behaviour SHALL be:
I see you interpret 'empty' as either null, or a string that trims to ''. Where is this specified?I can imagine only null is considered empty.
- if the UpdateAction is set to “update” or “append”, the receiver SHALL reject the related changes requested for the
specific ContextElement and report an error in the response; 

- If the UpdateAction is set to “delete”, the receiver SHALL ignore the ContextValue parameter, perform the related
changes requested (delete) and report a success in the response.
Behaviour in Case of non-existing ContextElement(s) or ContextAttribute(

AFAIKS this means nsgijs should allow empty values without touching them and Orion should behave as specified here.
I suggest implementing ngsi_build_update_context_request as
function ngsi_build_update_context_request(action, elements) {  return JSON.stringify({contextElements: elements, updateAction: action}, function(k,v) {    t = typeof(v);      if (t === 'string' || t === 'object')        return v;      return "" + v   })})
Only difference I can see is that- your contextValue attribute needs to be replaced by 'value' in the API but you could also implement a fallback. Why use 'contextValue' iso 'value'?- you filter out the properties that do not have to go to NSGI, however why would you do that; it makes it less maintainable in case of extensions and updates
However, going along this line, you can argue if you don't want to do this:
function ngsi_build_update_context_request(update) {  return JSON.stringify(update, function(k,v) {    t = typeof(v);      if (t === 'string' || t === 'object')        return v;      return "" + v   })})
requiring the caller to build  {contextElements: elements, updateAction: action}which is hardly any overhead. 

Rian

Date: Wed, 11 May 2016 12:37:53 -0700

**Comment by fgalan** [comment]
From the point of Orion, support for empty values was added in [release 0.26.0](https://github.com/telefonicaid/fiware-orion/releases/tag/0.25.0) (November 2015):

> Fix: empty/absent attribute value support, both in NGSIv1 and NGSIv2 (#1187, #1188 and #1358)

**Comment by aarranz** [comment]
Thanks Fermín for the info :).

**Comment by aarranz** [comment]
The `ngsijs` library started its development before the orion context broker implemented the json transport. We chose the `contextValue` attribute name because it was the name of the XML element. So... I'm also working on supporting the use of the 'value' attribute and deprecating the use of the `contextValue` attribute :).

**Comment by rianwouters** [comment]
Clear thanks. I also have the tests running in nodejs now

Working on simplifying the Json builders.

Verzonden van mijn HTC

----- Reply message -----
Van: "Álvaro Arranz" <notifications@github.com>
Aan: "conwetlab/ngsijs" <ngsijs@noreply.github.com>
CC: "rianwouters" <rianwouters@hotmail.com>, "Author" <author@noreply.github.com>
Onderwerp: [conwetlab/ngsijs] Empty contextValue is wrongly translated (#5)
Datum: vr, mei 13, 2016 17:32


The `ngsijs` library started its development before the orion context broker implemented the json transport. We chose the `contextValue` attribute name because it was the name of the XML element. So... I'm also working on supporting the use of the 'value' attribute and deprecating the use of the `contextValue` attribute :).

---

**Comment by aarranz** [comment]
Regarding the `null` values, currently the orion context broker convert them into strings, so the final value is `"null"`. Do you think it is better to convert them into empty strings?

**Comment by rianwouters** [comment]
I would say leave them null. The api user may do it on purpose .

Verzonden van mijn HTC

----- Reply message -----
Van: "Álvaro Arranz" <notifications@github.com>
Aan: "conwetlab/ngsijs" <ngsijs@noreply.github.com>
CC: "rianwouters" <rianwouters@hotmail.com>, "Author" <author@noreply.github.com>
Onderwerp: [conwetlab/ngsijs] Empty contextValue is wrongly translated (#5)
Datum: vr, mei 13, 2016 18:13


Regarding the `null` values, currently the orion context broker convert them into strings, so the final value is `"null"`. Do you think it is better to convert them into empty strings?

---

**Comment by rianwouters** [comment]
I refactored a lot see my for
How do you handle cross origin requests Orion only supports them for Get  requests?

Verzonden van mijn HTC

----- Reply message -----
Van: "Álvaro Arranz" <notifications@github.com>
Aan: "conwetlab/ngsijs" <ngsijs@noreply.github.com>
CC: "rianwouters" <rianwouters@hotmail.com>, "Author" <author@noreply.github.com>
Onderwerp: [conwetlab/ngsijs] Empty contextValue is wrongly translated (#5)
Datum: vr, mei 13, 2016 18:13


Regarding the `null` values, currently the orion context broker convert them into strings, so the final value is `"null"`. Do you think it is better to convert them into empty strings?

---
