### ISSUE TITLE
Error during execute: npm run start 

### ISSUE THREAD

**Issue by fermenreq** [conwetlab/ngsijs#7]
Hi all ! 

I have an error during execute the command npm run start.  
I'm using npm v1.1.4, nodejs v.0.6.12  on Ubuntu v.12.04

See the full error in the following link: [http://pastebin.com/2Btp2zKx](http://pastebin.com/2Btp2zKx)

Thanks in advance!

**Comment by aarranz** [comment]
Sorry, but express 3 (a dependency of `ngsi-proxy`) requires `nodejs` >= 0.8.0. I don't see an easy way to make `ngsi-proxy` work using nodejs v0.6.12 because express 2 uses a different API (Moreover I don't know if it will work on nodejs v0.6.12).

**Comment by fermenreq** [comment]
@aarranz **Thanks so much ! Its works !**

**Comment by aarranz** [comment]
You're welcome :)
